[build]
  publish = "."
  command = "echo 'No build needed - static files'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://fonts.gstatic.com https://cdn.tailwindcss.com https://unpkg.com; img-src 'self' data: https:; frame-ancestors 'self' *;"

[[headers]]
  for = "/embed.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Widget iframe embedding
[[redirects]]
  from = "/embed"
  to = "/index.html"
  status = 200